services:
  node-installer:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm install

  lebackoss:
    image: node:22.15.0-alpine3.21
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully
    ports:
      - "1506:1506"
    command: npm -w services/lebackoss run duplo:dev

  lebackoss-mongo:
    image: mongo:8.0.5
    attach: false
    env_file: ./services/lebackoss/.env
    volumes:
      - "lebackoss-mongo-data:/data/db"
    ports:
      - "27017:27017"

  lefrontoss:
    image: node:22.15.0-alpine3.21
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    command: npm -w services/lefrontoss run dev


volumes:
  lebackoss-mongo-data: