services:
  node-installer:
    build:
      context: .
      dockerfile: ./.docker/node.dockerfile
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm install

  lebackoss:
    image: node:22.15.0-alpine3.21
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully
    ports:
      - "1506:1506"
    command: npm -w services/lebackoss run duplo:dev

  lebackoss-mongo:
    image: mongo:8.0.5
    attach: false
    env_file: ./services/lebackoss/.env
    volumes:
      - "lebackoss-mongo-data:/data/db"
    ports:
      - "27017:27017"

  lefrontoss:
    image: node:22.15.0-alpine3.21
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully
    ports:
      - "3000:3000"
    command: npm -w services/lefrontoss run dev

  libretranslate:
    image: libretranslate/libretranslate:v1.6.5
    env_file:
      - ./services/rosetta/.env
    ports:
      - 5000:5000
    volumes:
      - libretranslate-data:/home/libretranslate/

  rosetta:
    image: mcr.microsoft.com/playwright:v1.53.1-noble
    volumes:
      - ${PWD}:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    ports: 
      - "1507:1506"
    user: 1000:1000
    depends_on:
      node-installer:
        condition: service_completed_successfully
      libretranslate: 
        condition: service_started
    command: npm -w services/rosetta run duplo:dev


volumes:
  lebackoss-mongo-data:
  libretranslate-data: