// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/draw-random-circle";
    body: {
        aIPrestationToken: string;
        data: {
            image: {
                value: string;
            };
            numberOfCircles: {
                value?: number | undefined;
            };
            minRadius: {
                value?: number | undefined;
            };
            maxRadius: {
                value?: number | undefined;
            };
        };
    };
    response: {
        code: 403;
        information: "authorization.wrong";
        body?: undefined;
    } | {
        code: 200;
        information: "circlepaint.sucess";
        body: {
            aIAgentToken: string;
        };
    };
}) | ({
    method: "POST";
    path: "/ping";
    body: {
        pingToken: string;
    };
    response: {
        code: 401;
        information: "wrong.token";
        body?: undefined;
    } | {
        code: 200;
        information: "ping.ok";
        body: {
            number: number;
        };
    };
}) | ({
    method: "POST";
    path: "/draw-zob";
    body: {
        aIPrestationToken: string;
        data: {
            image: {
                value: string;
            };
        };
    };
    response: {
        code: 403;
        information: "authorization.wrong";
        body?: undefined;
    } | {
        code: 200;
        information: "zobpaint.sucess";
        body: {
            aIAgentToken: string;
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
