// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "GET";
    path: "/test";
    response: {
        code: number;
        information: string;
        body: unknown;
        ok: boolean;
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
