// Generated by @duplojs/types-codegen
/* eslint-disable */
/* prettier-ignore */
/* istanbul ignore file */
/* v8 ignore start */
// noinspection JSUnusedGlobalSymbols
// @ts-nocheck
type CodegenRoutes = ({
    method: "POST";
    path: "/ping";
    body: {
        pingToken: string;
    };
    response: {
        code: 401;
        information: "wrong.token";
        body?: undefined;
    } | {
        code: 200;
        information: "ping.ok";
        body: {
            number: number;
        };
    };
}) | ({
    method: "POST";
    path: "/translate";
    body: {
        provider: "default" | "googleScrape" | "libretranslate";
        language: "fr-FR" | "en-US" | "it-IT" | "es-ES";
        text: string;
    };
    response: {
        code: 200;
        information: "text.translated";
        body: {
            result: string;
        };
    };
});

export { CodegenRoutes };
/* v8 ignore stop */
